name: linting, testing, building
run-name: ${{ github.actor }} ci settings 🚀
on:
  push:
    branches: ["fix_"]
  pull_request:
    branches: ["fix_"]
jobs:
  pipeline:
    runs-on: windows-latest 
    strategy:
      matrix:
        node-version: [17.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }} 
    - run:  npm install
    - run:  npm run build:prod
    - run:  npm run lint:ts
    - run:  npm run lint:scss
    - run:  npm run test:unit
